### ISSUE TITLE
Unsubscribe to a User's Posts

### ISSUE THREAD

**Issue by hannahhall** [nss-evening-cohort-12/rare-api-publishing-joshua-tree#15]
As a reader I would like to unsubscribe from an author's Posts so that I won't see the Posts of author's I am no longer interested in reading.

**Given** a user is viewing an author's profile view  
**When** they select the option to unsubscribe to the author  
**Then** the Subscription end datetime should be updated with the current datetime  
**And** the system should behave as it did before the user had created the Subscription

**Comment by ryanbeiden** [comment]
This ticket is complete for the API. All that needs to be done is the frontend functionality passing the data to update. Blocked until #21 is solved.

*Important Note*: The update function for the subscription viewset essentially checks which field the frontend sent as `null`, either the `created_on` filed or the `ended_on` field. From there it sets the current `datetime` to the "non-null" field of the too. This is in place so a user can re-subscribe.
