### ISSUE TITLE
Subscribe to a User's Posts

### ISSUE THREAD

**Issue by hannahhall** [nss-evening-cohort-12/rare-api-publishing-joshua-tree#17]
As a reader I would like to be able to subscribe to authors that I enjoy so that I can more easily find new Posts they have written.

**Given** A user is viewing a user profile
**When** they select the option to subscribe to the the author
**Then** a Subscription should be created in the database  
**And** the Subscription's begin datetime should be set to the current time  

# Dev Notes

1. Create a new model for subscriptions that connects two different user IDs, one for the author and the other for the subscriber:

![Screen Shot 2021-01-09 at 1 39 11 PM](https://user-images.githubusercontent.com/25331401/104107216-41e8cf00-5280-11eb-88df-1728ab82a294.png)

**Comment by ryanbeiden** [comment]
Can't be fully completed until ticket #21 is complete. The backend can be started, but the frontend has not been created yet (the user details page)

**Comment by ryanbeiden** [comment]
This ticket is complete for the API. The only piece to complete is the frontend with the `Subscribe` button and functionality.
